// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3xUCyg60HSKNlr3Ho0fBrSLBW8bCFACo',
    appId: '1:991453795720:web:449d09cf9df438c218163d',
    messagingSenderId: '991453795720',
    projectId: 'dtals-app',
    authDomain: 'dtals-app.firebaseapp.com',
    storageBucket: 'dtals-app.firebasestorage.app',
    measurementId: 'G-RP0K5E4FBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqncEzjWahEUNh0iBSeNVVMmEbGWORQoo',
    appId: '1:991453795720:android:c107c9c207e5006d18163d',
    messagingSenderId: '991453795720',
    projectId: 'dtals-app',
    storageBucket: 'dtals-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXR02pn19QqHXXbhUDhHeaPlCJW0klHoE',
    appId: '1:991453795720:ios:cf114c8956d9082518163d',
    messagingSenderId: '991453795720',
    projectId: 'dtals-app',
    storageBucket: 'dtals-app.firebasestorage.app',
    iosBundleId: 'com.daithanh.dtals.dtalsMobile',
  );
}
